---
# tasks file for cockroach

- name: Kill all roaches
  script: kill-all-roaches.sh
  when: reinstall_cluster or remove_cluster
  tags: remove_cluster
  ignore_errors: true

- name: Remove installation directory
  file: name={{ install_location }} state=absent
  when: reinstall_cluster or remove_cluster
  tags: remove_cluster

- name: remove symlink from /usr/local/bin
  file: src={{ install_location }}/{{ install_version}}/cockroach dest=/usr/local/bin/cockroach state=absent
  when: reinstall_cluster or remove_cluster
  tags: remove_cluster


- name: Create installation directory
  file: name={{ install_location }} state=directory
  tags: directories

- name: Get installation files
  get_url: url="{{ binary_url }}/{{ binary_version }}" dest="/tmp/{{ binary_version }}" validate_certs=false
  #shell: "wget {{ binary_url }}/{{ binary_version }} -O /tmp/{{ binary_version }}"
  tags: download

- name: Unpack/install binaries
  unarchive: src=/tmp/{{ binary_version }} dest={{ install_location }} copy=no
  tags: install

- name: create symlink to /usr/local/bin
  file: src={{ install_location }}/{{ install_version}}/cockroach dest=/usr/local/bin/cockroach state=link
  tags: link

- name: test the installation
  shell: "{{ install_location }}/{{ install_version}}/cockroach version"
  register: cversion
  tags: test

- name: print output
  debug: var=cversion.stdout_lines
  tags: test
